name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image:  golang:1.16
    services:
      etcd:
        image: quay.io/coreos/etcd:v3.2.32
        env:
          ALLOW_NONE_AUTHENTICATION: yes
        ports:
        - 2379:2379
        options: >-
          --health-cmd "etcdctl cluster-health"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 20
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      env:
        ETCD_ENDPOINT: http://etcd:2379


